# Site settings
title: cfly's blog
email: caofei.org@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This blog's description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pages.caofei.org" # the base hostname & protocol for your site
twitter_username: cao_fei
github_username: cfly

# Build settings
#markdown: kramdown
markdown: redcarpet


